 module.exports = [{
     login: 'abel_c',
     oldLogin: 'abel',
     portable: '0633138868',
     email: "abel@chalier.me",
     service: 'INFORMATIQUE',
     root: true,
     nom: 'abel',
     prenom: 'chalier',
     activated: true
 }, {
     login: 'benjamin_b',
     oldLogin: 'boukris_b',
     portable: '0782903875',
     email: 'contact@edison-services.fr',
     service: 'INTERVENTION',
     root: true,
     nom: 'boukris',
     prenom: 'benjamin',
     activated: true

 }, {
     login: 'harald_x',
     oldLogin: 'harald',
     service: 'INTERVENTION',
     root: false,
     nom: 'xxx',
     prenom: 'harald',
     activated: false
 }, {
     login: 'jeremie_r',
     oldLogin: 'jeremie',
     service: 'INTERVENTION',
     root: false,
     nom: 'roudier',
     prenom: 'jeremie',
     activated: false
 }, {
     login: 'laurent_x',
     oldLogin: 'laurent',
     service: 'INTERVENTION',
     root: false,
     nom: 'Clement',
     prenom: 'xxx',
     activated: false
 }, {
     login: 'tayeb_g',
     oldLogin: 'tayeb',
     service: 'INTERVENTION',
     root: false,
     nom: 'guillot',
     prenom: 'taieb',
     activated: false
 }, {
     login: 'eliran_t',
     oldLogin: 'eliran',
     service: 'INTERVENTION',
     root: true,
     nom: 'taieb',
     prenom: 'eliran',
     activated: true
 }, {
     login: 'thomas_x',
     oldLogin: 'thomas',
     service: 'INTERVENTION',
     root: true,
     nom: 'xxx',
     prenom: 'thomas',
     activated: false
 }, {
     login: 'vincent_q',
     oldLogin: 'vincent',
     service: 'COMPTABILITE',
     root: true,
     nom: 'queudray',
     prenom: 'vincent',
     activated: false
 }, {
     login: 'yohann_r',
     oldLogin: 'yohann',
     service: 'PARTENARIAT',
     root: true,
     nom: 'rhoum',
     prenom: 'yohann',
     activated: true
 }]
